#-----------------------------
# Choose which workflow to generate data for.
# One at a time. 
#-----------------------------

#wf: "MG-4"
wf: "MG-5"

# location of raptor binaries
raptor_bin_dir: "/home/evelin/metagenomics/raptor_data_simulation/build/bin"
# location of simulated data
data_out_dir: "/home/evelin/metagenomics/A2-job-granularity/data"

#-----------------------------
# Parameters of simulated data.
#
# Note: if you want to rerun the same workflow with NEW data you have to change at least one of the following parameters:
#  * number of bins
#  * read error rate
#  * read length
#
#-----------------------------

ref_size: 102400        # size of reference in bytes? 4*2^20 = 4MiB
number_of_bins: 8
errors_per_read: 5       # number of errors; this is the basis for error rate in an approximate match
read_length: 150
read_count: 1024        # size of query (count)

#-----------------------------
# Mason variator parameters.
#
# These have been highered to make sure that there is enough of a difference between the haplotypes in each bin.
# Only if there is a difference between the haplotypes can a read map to multiple haplotypes with a different edit distance.
#-----------------------------

haplotype_count: 4
snp_rate: 0.01
small_indel_rate: 0.001

#-----------------------------
# Customizing the number of read files in MG-4 and MG-5.
#
# For the other worflows number of read files == number of bins
#
# Note that it must hold that (read_count % read_file_count) == 0
#-----------------------------

read_file_count: 4

