# location of raptor binaries
raptor_bin_dir: "/home/evelin/metagenomics/raptor_data_simulation/build/bin"
# location of simulated data
data_out_dir: "/home/evelin/metagenomics/A2-metagenome-snakemake/data"

#-----------------------------
# Parameters of simulated data
#
# Note: if you want to rerun the workflow with NEW data you have to change at least one of the following parameters:
#  * number of bins
#  * read error rate
#  * read length
#
#-----------------------------

ref_size: 1048576        # size of reference in bytes? 4*2^20 = 4MiB
number_of_bins: 1024
errors_per_read: 5       # number of errors; this is the basis for error rate in an approximate match
read_length: 150
read_count: 65536        # size of query (count)
haplotype_count: 4
