#-----------------------------
#
# Parameters of prefiltering
#
#-----------------------------

kmer_length: 10    # should be 9 < k < 13

#-----------------------------
#
# Parameters of search
#
#-----------------------------

allowed_errors: 5       # corresponds to all mapping
strata_width: 5         # corresponds to strata (best+x) mapping
