#-----------------------------
#
# Parameters of prefiltering
#
#-----------------------------

kmer_length: 10    # should be 9 < k < 13

#-----------------------------
#
# Parameters of search
# - the number of allowed errors is inferred from the data simulation
#-----------------------------
