#-----------------------------
#
# Parameters of prefiltering
#
#-----------------------------

kmer_length: 10    # should be 9 < k < 13

#-----------------------------
#
# Parameters of search
#
#-----------------------------

allowed_errors: 6       # number of errors
strata_width: 3         # number of errors; corresponds to x in (best+x) mapping
