#-----------------------------
#
# Parameters of prefiltering
#
#-----------------------------

kmer_length: 10    # should be 9 < k < 13
allowed_errors: 4

#-----------------------------
#
# Parameters of search
#
#-----------------------------

error_percentage: 2
